apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: devopscube/kube-jobs-demo:latest
        command: ["100"]
      restartPolicy: Never
